Sprint 1/step 2
Zakusov/react-burger pull request #1
Opened 2023-03-12 20:43 UTC by Zakusov

Первый вариант Бургерной

2023-03-13 05:15 UTC, andryxxa93 requested changes
Проделана большая работа! Вы хорошо разобрались с функциональными компонентами, правильно используете useEffect и PropTypes.

Что понравилось:
- Записываете ошибку запроса в стейт.
- Сделали отписку от слушателя событий.
- Проект соответствует дизайну - так держать!

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- При нажатии на ингредиент или кнопку "Оформить заказ" приложение падает с ошибкой.

<img width="1440" alt="Снимок экрана 2023-03-13 в 08 08 24" src="https://user-images.githubusercontent.com/60173362/224612928-b6f7abd6-27d2-470d-9102-9e718605291d.png">

- Добавьте проверку успешности запроса
- во многих компонентах дублируется описание PropTypes ингредиента. Следует вынести его в отдельный файл
- В некоторых компонентах не хватает пропсов в `propTypes`
- Список ингредиентов должен быть ограничен по высоте - пожалуйста посмотрите как в фигме.

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-03-13 05:15 UTC, andryxxa93 commented on src/components/app/app.js
> +        const getBurgerData = async () => {
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-03-13 05:15 UTC, andryxxa93 commented on src/components/app/app.js
> +                const data = await res.json();
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2023-03-13 05:15 UTC, andryxxa93 commented on src/components/big-card/big-card.js
> +    arr: PropTypes.arrayOf(PropTypes.shape({
**Надо исправить**

во многих компонентах дублируется описание PropTypes ингредиента
Следует вынести его в отдельный файл (можно создать файл prop-types.js в папке utils) и переиспользовать описание пропсов ингрединта, а не дублировать

2023-03-13 05:15 UTC, andryxxa93 commented on src/components/card/card.js
> +Card.propTypes = {
**Необходимо исправить**
Тут указаны не все пропсы, что принимает компонент - необходимо дописать. Проверьте в остальном проекте.

2023-03-13 05:15 UTC, andryxxa93 commented on src/components/modal/modal.js
> +        <ModalOverlay onClick={toClose}>
**Надо исправить**

у ModalOverlay не должно быть children, это просто компонент подложки а не контейнер`

2023-03-13 05:15 UTC, andryxxa93 commented on src/components/modal/modal.js
> +        return () => window.removeEventListener('keydown', close)
**Отлично!**
Вы сделали отписку от слушателя, это позволит избежать утечек памяти.

2023-03-13 05:15 UTC, andryxxa93 commented on src/utils/data.js
> +const data = [
**Можно лучше**
Файл больше не нужен - его стоит удалить

2023-03-13 16:51 UTC, Zakusov commented on src/utils/data.js
> +const data = [
Удалил

2023-03-13 19:37 UTC, Zakusov commented on src/components/app/app.js
> +        const getBurgerData = async () => {
Вынес

2023-03-13 19:38 UTC, Zakusov commented on src/components/app/app.js
> +                const data = await res.json();
Исправил

2023-03-13 20:21 UTC, Zakusov commented on src/components/big-card/big-card.js
> +    arr: PropTypes.arrayOf(PropTypes.shape({
Исправил

2023-03-13 21:04 UTC, Zakusov commented on src/components/card/card.js
> +Card.propTypes = {
Исправил

2023-03-13 21:06 UTC, Zakusov commented on src/components/modal/modal.js
> +        return () => window.removeEventListener('keydown', close)
👍

2023-03-14 08:36 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-03-14 08:36 UTC, andryxxa93 commented on src/components/modal/modal.js
> +        <ModalOverlay onClose={onClose}>
**Можно лучше**

у ModalOverlay не должно быть children, это просто компонент подложки а не контейнер`

2023-03-16 19:48 UTC, merged