Sprint 5/step 1
Zakusov/react-burger pull request #7
Opened 2023-05-21 19:30 UTC by Zakusov

- Типизация хранилища
- Экраны «Лента заказов» и «История заказов»
- Доработка роутинга в приложении
- Работа с WebSocket

2023-05-21 19:46 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Сокеты закрываются и открываются согласно брифу
- Раздельное хранение данных полученных по сокетам
- Реализован универсальный веб-сокет
- Отличная типизация хранилища

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- В запрос на оформление заказа необходимо передавать токен, чтобы бек понимал от того пришел заказ
- При заходе на страницу профиля происходит бесконечное количество запросов данных юзера

<img width="1439" alt="Снимок экрана 2023-05-21 в 22 40 05" src="https://github.com/Zakusov/react-burger/assets/60173362/be20b915-eb1b-42d3-b9b5-a459eb66c162">

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-21 19:46 UTC, andryxxa93 commented on src/services/middleware/socketMiddleware.ts
> +                socket.onmessage = event => {
**Можно лучше**
Необходимо добавить проверку при получении сообщения от сокета. Eсли токен протух и приходит поле message 'Invalid or missing token' то его необходимо обновить через refreshToken.

2023-05-21 19:46 UTC, andryxxa93 commented on src/components/app/app.tsx
> +                <Route path="/feed" element={<FeedOrdersPage/>}/>
**Можно лучше**
Роуты желательно записывать в константы или enum - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-05-21 19:46 UTC, andryxxa93 commented on src/utils/auth.tsx
>  // @ts-ignore
**Можно лучше**
`@ts-ignore` желательно убирать полностью из проекта - он допустим только в крайних случаях

2023-05-21 23:01 UTC, Zakusov commented on src/utils/auth.tsx
>  // @ts-ignore
Исправил

2023-05-22 09:09 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-05-28 09:30 UTC, merged